### PR TITLE
Made it running on Fedora

### PR DESCRIPTION
**Pull request by lzap**
If interested i can improve

### CODE REVIEW

**Comment by michaelowens** [comment]
This also fixes issues on Arch Linux, thanks!

**Comment by alkerway** [comment]
Thanks a ton, works on ubuntu 20 as well 🙏

**Comment by lzap** [comment]
The blog is down, I hope @ivanstojic you're doing okay! Normally I would close my PR after 8 years, however, it turns to be useful. So will keep it up for a while.

**Comment by lzap** [comment]
Allright, cheers!

**Pull request closed without merging**
